#ifndef p02par_h
#define p02par_h 1
//--------------------------------------------------------------------
// File p02par.h defines the interface to the parser generated by
// yacc.
//--------------------------------------------------------------------

//--------------------------------------------------------------------
//Application include files
//--------------------------------------------------------------------
#include "p02lex.h"
//--------------------------------------------------------------------
//--------------------------------------------------------------------
//Function yyparse is the parser generated by yacc.
//--------------------------------------------------------------------
#ifdef __cplusplus
extern "C"
#endif
int yyparse(void);
#endif
class Parser : public Lexer
{
public:
    Parser(FILE *i) : Lexer(i) {}
    int Parse(void) { return yyparse(); }
};