#ifndef p04par_h
#define p04par_h 1
//--------------------------------------------------------------------
// File p04par.h defines the interface to the parser generated by
// yacc.
//--------------------------------------------------------------------
// Team Identification Block
// Author 1: 	Daniel L. Tomei
// Student ID: 	*20491050
// E-Mail: 	dtomei@uco.edu
// CRN: 	13855, Fall, 2020
// Author 2: 	Aditi Panvelkar
// Student ID: 	*20490610
// E-Mail: 	apanvelkar@uco.edu
// CRN: 	13855, Fall, 2020
// Course: 	CMSC 5023 – Programming Languages
// Project: 	p04
// Due: 	December 10, 2020
// Project Account Number: tt162
//--------------------------------------------------------------------
//Application include files
//--------------------------------------------------------------------
#include "p04lex.h"
//--------------------------------------------------------------------
//--------------------------------------------------------------------
//Function yyparse is the parser generated by yacc.
//--------------------------------------------------------------------
#ifdef __cplusplus
extern "C"
#endif
int yyparse(void);
#endif
class Parser : public Lexer
{
public:
    Parser(FILE *i) : Lexer(i) {}
    int Parse(void) { return yyparse(); }
};